service: default
runtime: python37

basic_scaling:
    max_instances: 2
    idle_timeout: 10m
    
instance_class: B4

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 1.2


entrypoint: gunicorn app:server

